title: push.game [TEAM]
description: A blog about push.game team

#baseurl: "/blog"
#url: "https://push.game"

game_link: https://saysomething2.world

home_title: push.game
home_description: Blog of SaySomething2.world [TEAM]


# User settings
username: push.game

user_title: SaySomething2.world Developer
user_description: push.game [TEAM]

email: admin@push.game
github_username:  PushDotGame

#twitter_username: lorem_ipsum
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Us
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
